# dbt Project Configuration
# =============================================================================
# DWHBI - Data Warehouse for Business Intelligence
# =============================================================================

name: 'dwhbi'
version: '1.0.0'
config-version: 2

# プロジェクト構成
profile: 'dwhbi'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# モデル設定
# Note: profiles.ymlで schema: staging を指定しているため、
#       +schema を指定するとサフィックスとして追加される
#       staging層はデフォルトの staging スキーマを使用
models:
  dwhbi:
    # staging層: raw → staging変換（デフォルトスキーマ使用）
    staging:
      +materialized: view
      +post-hook:
        - "ALTER VIEW {{ this }} SET (security_invoker = on)"
        - "GRANT SELECT ON {{ this }} TO authenticated"
        - "GRANT SELECT ON {{ this }} TO service_role"
      toggl_track:
        +tags: ['toggl', 'time_tracking']
      google_calendar:
        +tags: ['google', 'calendar']

    # ref層: ソース非依存の共有マスタ・マッピング
    ref:
      +materialized: view
      +schema: ref
      +post-hook:
        - "ALTER VIEW {{ this }} SET (security_invoker = on)"
        - "GRANT SELECT ON {{ this }} TO authenticated"
        - "GRANT SELECT ON {{ this }} TO service_role"
      +tags: ['ref', 'master']

    # core層: ビジネスエンティティ
    core:
      +materialized: view
      +schema: core
      +post-hook:
        - "ALTER VIEW {{ this }} SET (security_invoker = on)"
        - "GRANT SELECT ON {{ this }} TO authenticated"
        - "GRANT SELECT ON {{ this }} TO service_role"

    # marts層: 分析用ビュー（将来用）
    # Note: モデル追加時にコメント解除
    # marts:
    #   +materialized: view
    #   +schema: marts

# Seed設定
seeds:
  dwhbi:
    +schema: seeds
    +post-hook:
      - "GRANT SELECT ON {{ this }} TO authenticated"
      - "GRANT SELECT ON {{ this }} TO service_role"

# 変数設定
vars:
  # タイムゾーン設定（Asia/Tokyo）
  local_timezone: 'Asia/Tokyo'
