name: 'Python Setup'
description: 'Setup Python environment and install connector dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install connector dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install httpx supabase psycopg2-binary cryptography python-dotenv tzdata

    - name: Set PYTHONPATH for connector
      shell: bash
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/packages/connector" >> $GITHUB_ENV
